name: Test Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Test tag version'
        required: true
        default: 'v1.0.1'

permissions:
  contents: write

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build
        run: cargo build --release
        
      - name: Package
        run: |
          cd target/release
          tar czf ../../tagcache-test-linux-x86_64.tar.gz tagcache
          cd ../..
        
      - name: Create Test Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Test Release ${{ github.event.inputs.tag }}
          body: |
            This is a test release to verify the CI/CD pipeline works correctly.
            
            Files included:
            - `tagcache-test-linux-x86_64.tar.gz` - Linux x86_64 binary
          files: |
            tagcache-test-linux-x86_64.tar.gz
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
